### ISSUE TITLE
File "timestamper" could not be opened for reading/parsing.

### ISSUE THREAD

**Issue by 0x80O0oOverfl0w** [opencpi/training#1]
Following along with Lab2_AppDevelopment.pdf the timestamper assembly will not successfully compile. The peak detector and agc_complex both compile fine. Centos 7.5 with OpenCPI RPM 1.3.1 install.

=============Building assembly lab2_most_hdl_assy
For file lab2_most_hdl_assy.xml: in HdlAssembly for lab2_most_hdl_assy: for worker timestamper: File "timestamper" could not be opened for reading/parsing.  Files tried: timestamper.xml, timestamper.xml, gen/timestamper.xml, ../lib/xm/timestamper.xml, ../lib/rcc/timestamper.xml, ../lib/hdl/timestamper.xml, ../lib/ocl/timestamper.xml, ../lib/assy/timestamper.xml, ../specs/timestamper.xml, ./../../../imports/ocpi.assets/exports/lib/util_comps/timestamper.xml, ./../../../components/lib/hdl/timestamper.xml, ./../../../components/lib/timestamper.xml, ./../../../imports/ocpi.core/exports/lib/components/hdl/timestamper.xml, ./../../../imports/ocpi.core/exports/lib/components/timestamper.xml, ./../../../imports/ocpi.assets/exports/lib/adapters/timestamper.xml, ./../../../imports/ocpi.core/exports/lib/adapters/hdl/timestamper.xml, ./../../../imports/ocpi.core/exports/lib/adapters/timestamper.xml, ./../../../imports/ocpi.core/exports/specs/timestamper.xml. CWD is /home/user/workspace/training_project/hdl/assemblies/lab2_most_hdl_assy
make[2]: *** [gen/lab2_most_hdl_assy.wks] Error 1
make[2]: Entering directory `/home/user/workspace/training_project/hdl/assemblies/lab2_most_hdl_assy'
/opt/opencpi/cdk/include/hdl/hdl-assembly.mk:70: *** Error deriving workers from file lab2_most_hdl_assy.xml: make[2]: Entering directory `/home/user/workspace/training_project/hdl/assemblies/lab2_most_hdl_assy' make[2]: Leaving directory `/home/user/workspace/training_project/hdl/assemblies/lab2_most_hdl_assy'.  Stop.
make[2]: Leaving directory `/home/user/workspace/training_project/hdl/assemblies/lab2_most_hdl_assy'
make[1]: *** [lab2_most_hdl_assy] Error 2
make[1]: Leaving directory `/home/user/workspace/training_project/hdl/assemblies'
make: *** [hdlassemblies] Error 2
[user@localhost training]$

**Comment by AaronDMarasco-VSI** [comment]
The "timestamper" worker is part of the Assets project, and that might be the first reference to it. Have you built the Assets project and ensured it is accessible? That is Section 3 of the "Standalone_Training" PDF.

**Comment by 0x80O0oOverfl0w** [comment]
I went through my .bash_history and saw I had only built the core project and not the assets project. I built the assets project and now the example project builds successfully.

**Comment by AaronDMarasco-VSI** [comment]
Great to hear, thanks for following up!
